[2025-03-15 04:10:10] production.ERROR: Failed to create user. {"exception":"[object] (Exception(code: 0): Failed to create user. at /home/php/app/Events/CreateShortenerAccountEvent.php:64)
[stacktrace]
#0 /home/php/app/Events/CreateShortenerAccountEvent.php(17): App\\Events\\CreateShortenerAccountEvent->createUser()
#1 /home/php/app/Console/Commands/CreateShortenerAccountCommand.php(48): App\\Events\\CreateShortenerAccountEvent->__construct()
#2 /home/php/vendor/illuminate/database/Concerns/BuildsQueries.php(39): App\\Console\\Commands\\CreateShortenerAccountCommand->App\\Console\\Commands\\{closure}()
#3 /home/php/app/Console/Commands/CreateShortenerAccountCommand.php(53): Illuminate\\Database\\Eloquent\\Builder->chunk()
#4 /home/php/vendor/illuminate/container/BoundMethod.php(36): App\\Console\\Commands\\CreateShortenerAccountCommand->handle()
#5 /home/php/vendor/illuminate/container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /home/php/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /home/php/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /home/php/vendor/illuminate/container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#9 /home/php/vendor/illuminate/console/Command.php(134): Illuminate\\Container\\Container->call()
#10 /home/php/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#11 /home/php/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#12 /home/php/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#13 /home/php/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /home/php/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#15 /home/php/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#16 /home/php/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run()
#17 /home/php/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#18 {main}
"} 
[2025-03-15 22:01:10] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'A1iKnxqoChSSzsFc8eEMxG8',
  ),
)  
[2025-03-15 22:47:03] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'ALxfeKF5xkKCKbLmJxYaZql',
  ),
)  
[2025-03-15 22:47:03] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'ADEv9LUpbqlds67SlW9xe6B',
  ),
)  
[2025-03-15 22:47:03] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'A2S4507QkXFEFS8FhBwA6fZ',
  ),
)  
[2025-03-15 22:47:03] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'Aoevu4COrxv7L6x_760xsoT',
  ),
)  
[2025-03-15 22:47:03] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'A3YHmh0EcqSxq5T0TAkmZmt',
  ),
)  
[2025-03-15 23:28:29] production.ERROR: array (
  'error' => 
  array (
    'message' => '(#2) Service temporarily unavailable',
    'type' => 'OAuthException',
    'is_transient' => true,
    'code' => 2,
    'error_data' => 
    array (
      'messaging_product' => 'whatsapp',
      'details' => 'Server is temporarily unavailable. Please retry after some time.',
    ),
    'fbtrace_id' => 'A1_R9-MS8RLGqJ0ysOiNJL_',
  ),
)  
